server:
  port: 8001
  servlet:
    context-path: /user
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid

  redis:
    host: 8.129.230.41
    ## redis数据库索引位置
    database: 1
    port: 6379
    timeout: 1000ms
    password:
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        max-wait: -1ms
        ## 连接池中最大空闲链接
        max-idle: 10
        ## 连接池中最小空闲链接
        min-idle: 0

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

