server:
  port: 9001
  servlet:
    context-path: /ucp


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.129.230.41:3306/ucp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      uri: mongodb://admin:123456@8.129.230.41:27017/ucp?authSource=admin&authMechanism=SCRAM-SHA-1

## 配置控制台打印SQL日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hyqin.entity
